[config]

# Which color to choose if multiple good colors were found from an image.
# choices: [darkness, lightness, saturation, less-saturation, value, closest-to-fallback]
prefer = "saturation"

[templates.waybar]
# Defaults to the type from CLI if unspecified.
# One of `SchemeContent`, `SchemeExpressive`, `SchemeFidelity`, `SchemeFruitSalad`,
# `SchemeMonochrome`, `SchemeNeutral`, `SchemeRainbow`, `SchemeTonalSpot`, `SchemeVibrant`
type = "SchemeExpressive"
input_path = '~/.config/matugen/templates/colors-waybar.css'
output_path = '~/.config/waybar/colors/colors-matugen.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.hyprland]
type = "SchemeFidelity"
input_path = '~/.config/matugen/templates/colors.lua'
output_path = '~/.config/hypr/colors/matugen.lua'

[templates.hyprlock]
type = "SchemeVibrant"
input_path = "~/.config/matugen/templates/colors-hyprlock.conf"
output_path = "~/.config/hypr/colors/colors-matugen.conf"

[templates.rofi]
type = "SchemeVibrant"
input_path = "~/.config/matugen/templates/colors.rasinc"
output_path = "~/.config/rofi/themes/matugen.rasinc"
