# Hyprsunset profiles

max-gamma = 150

profile {
    time = 7:30
    identity = true
}

profile {
    time = 19:00
    temperature = 3500
}

profile {
    time = 20:00
    temperature = 3000
}

profile {
    time = 21:00
    temperature = 2500
}
