# Hypridle
# ==============================================================================================================================================

general {
    # Locks the session using hyprlock
    lock_cmd = pidof hyprlock || hyprlock

    # Ensures that the session is locked before going to sleep
    before_sleep_cmd = loginctl lock-session

    # Turns on the screen after sleep
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'

    # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_dbus_inhibit = false
}

# Turn off screen faster if session is already locked
listener {
    timeout = 30

    # Turns off the screen if hyprlock is active
    on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'

    # Turns on the screen after activity is detected
    on-resume = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Idle Warnning
listener {
    timeout = 300

    # Notify the user when idle warning is triggered
    on-timeout = notify-send -e "Idle Warning 󰒲󰒲󰒲" "Anybody home? 󱠡"

    # Notify the user when activity is detected after timeout has fired
    on-resume = notify-send -e "Resumed" "Hello again"
}

# Screenlock
listener {
    timeout = 360
    on-timeout = loginctl lock-session
}

# Turn off screen
listener {
    timeout = 390
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Suspend
listener {
   timeout = 600
   on-timeout = systemctl suspend
   on-resume = notify-send -e "Resumed" "Session resumed"
}
